# Generated by Django 3.1.5 on 2021-06-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmr_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='God',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('planned_srldc', models.IntegerField()),
                ('forced_srldc', models.IntegerField()),
                ('total_Outage_srldc', models.IntegerField()),
                ('planned_nrldc', models.IntegerField()),
                ('forced_nrldc', models.IntegerField()),
                ('total_Outage_nrldc', models.IntegerField()),
                ('planned_erldc', models.IntegerField()),
                ('forced_erldc', models.IntegerField()),
                ('total_Outage_erldc', models.IntegerField()),
                ('planned_wrldc', models.IntegerField()),
                ('forced_wrldc', models.IntegerField()),
                ('total_Outage_wrldc', models.IntegerField()),
            ],
        ),
    ]
