# Generated by Django 3.1.5 on 2021-06-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmr_backend', '0002_god'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iex',
            fields=[
                ('iex_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_Block', models.CharField(max_length=20)),
                ('mcp', models.FloatField()),
                ('mcv', models.FloatField()),
                ('purchase_Bid', models.FloatField()),
                ('sell_Bid', models.FloatField()),
                ('cleared_Volume', models.FloatField()),
                ('final_Scheduled_Volume', models.FloatField()),
            ],
        ),
    ]
