# Generated by Django 3.1.5 on 2021-06-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmr_backend', '0003_iex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psp',
            fields=[
                ('psp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('availability_erldc', models.FloatField()),
                ('demand_Met_erldc', models.FloatField()),
                ('shortage_erldc', models.FloatField()),
                ('availability_nrldc', models.FloatField()),
                ('demand_Met_nrldc', models.FloatField()),
                ('shortage_nrldc', models.FloatField()),
                ('availability_srldc', models.FloatField()),
                ('demand_Met_srldc', models.FloatField()),
                ('shortage_srldc', models.FloatField()),
                ('availability_wrldc', models.FloatField()),
                ('demand_Met_wrldc', models.FloatField()),
                ('shortage_wrldc', models.FloatField()),
            ],
        ),
    ]
