# Generated by Django 3.1.5 on 2021-06-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmr_backend', '0004_psp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dsm',
            fields=[
                ('dsm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('freq_below', models.FloatField()),
                ('freq_not_below', models.FloatField()),
                ('A1', models.FloatField()),
                ('A2', models.FloatField()),
                ('E1', models.FloatField()),
                ('E2', models.FloatField()),
                ('N1', models.FloatField()),
                ('N2', models.FloatField()),
                ('N3', models.FloatField()),
                ('S1', models.FloatField()),
                ('S2', models.FloatField()),
                ('S3', models.FloatField()),
                ('W1', models.FloatField()),
                ('W2', models.FloatField()),
                ('W3', models.FloatField()),
                ('inter_regional', models.FloatField()),
            ],
        ),
    ]
