# Generated by Django 3.1.5 on 2021-06-11 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmr_backend', '0005_dsm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_accuracy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('below_85', models.FloatField()),
                ('between_85_90', models.FloatField()),
                ('between_90_95', models.FloatField()),
                ('between_95_98', models.FloatField()),
                ('between_98_100', models.FloatField()),
                ('between_100_105', models.FloatField()),
                ('between_105_110', models.FloatField()),
                ('above_110', models.FloatField()),
                ('total_blocks', models.FloatField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmr_backend.model_dam')),
            ],
        ),
    ]
