# Generated by Django 3.1.5 on 2021-06-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmr_backend', '0007_model_predictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='god',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
